# Generated by Django 4.1.7 on 2023-03-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
